### PR TITLE
Examples - Chat - Redesign

### LINKED ISSUE #14: Improvement in chat app design
Current Behavior : 

a. Logo doesn't exist in chat

b. The width of the padding is still less than the size of the padding. Just make it full size. 

c. Item border should be reduced 

Expected behavior : Make all of them fix

image

### PR DESCRIPTION
**Pull request by aswara**
Fixes #14

### CODE REVIEW

**Comment by kontenbase-dev** [comment]
Fixes #14

**Comment by aswara** [comment]
Fixes #14

**Review by mhaidarhanif — COMMENTED** [review]
@aswara Since it's related to design, this PR need to inform the deployed preview/staging app.

Please check Vercel and GitHub connection.

So @radiegtya can also review quickly.

**Comment by aswara** [comment]
demo: https://kontenbase-chat-7ra76oyu8-kontenbase-dev.vercel.app

**Pull request merged**
